name: Cleanup Beta Branch Infra

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  cleanup-beta-infra:
    runs-on: ubuntu-latest
    environment: ops_utils
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up GitHub App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.SCIAM_OPS_CLIENT_ID }}
          private-key: ${{ secrets.SCIAM_OPS_PRIVATE_KEY }}

      - name: Get stale beta branches
        id: get-branches
        run: |
          STALE_BRANCHES=$(git log --format="%ci %h %d %an" --no-walk --before="30 days ago" --branches --remotes | grep -Eo 'origin/(beta[^ ,)]*|paired-beta[^ ,)]*)' | sed 's|origin/||' | sort -u | paste -sd "," -)
          echo "branches=$STALE_BRANCHES" >> $GITHUB_OUTPUT

      - name: Delete beta infrastructure
        if: ${{ steps.get-branches.outputs.branches != '' }}
        run: |
          IFS=',' read -ra BRANCH_ARRAY <<< "${{ steps.get-branches.outputs.branches }}"
          echo "Stale branches: ${BRANCH_ARRAY[*]}"
          aws ecs list-services --profile dev --region us-east-1 --cluster test-ecs-cluster --query 'serviceArns[*]' --output text | tr ' ' '\n' | grep '^beta' | sed -e 's/^beta-//' -e 's/-django-service//' -e 's/-node-service//' > listofservices
          printf "%s\n" "${BRANCH_ARRAY[@]}" > listofbranches
          chmod +x ./cleanup-beta.sh
          ./cleanup-beta.sh listofservices listofbranches

      - name: Notify Slack
        if: ${{ steps.get-branches.outputs.branches != '' }}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_SAWEBTEAM }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "Deleted infrastructure for stale beta branches:\n${{ steps.get-branches.outputs.branches }}",
              "icon_emoji": ":wastebasket:"
            }
