name: Baseline.yml

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  security-events: write
  issues: write

jobs:
  zap_scan_scientificamerican:
    name: Run ZAP Baseline Scan for scientificamerican.com
    runs-on: ubuntu-latest
    # runs-on: [sciam, self-hosted, linux]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: checking baseline.conf
        run: ls -lah $(pwd)/beta

      - name: Create baseline.conf if missing
        run: |
          mkdir -p $(pwd)/beta
          touch $(pwd)/beta/baseline.conf

      - name: Verify baseline.conf
        run: ls -lah $(pwd)/beta


      - name: Run ZAP Baseline Scan
        id: zap_sciam
        run: |
          docker run -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable \
          zap-baseline.py -t https://www.scientificamerican.com -g /zap/wrk/beta/baseline.conf -r /zap/wrk/testreport.html


      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: "zapsciam"
          path: "${{ github.workspace }}/ops_utils/zap/*" 


  zap_scan_main_scientificamerican:
    name: Run ZAP Baseline Scan for main.scientificamerican.com
    runs-on: ubuntu-latest
    # runs-on: [sciam, self-hosted, linux]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: checking baseline.conf
        run: ls -lah $(pwd)/beta

      - name: Create baseline.conf if missing
        run: |
          mkdir -p $(pwd)/beta
          touch $(pwd)/beta/baseline.conf

      - name: Verify baseline.conf
        run: ls -lah $(pwd)/beta

      - name: Run ZAP Baseline Scan
        id: zap_sciam
        run: |
          docker run -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable \
          zap-baseline.py -t https://main-www.scientificamerican.com -g /zap/wrk/beta/baseline.conf -r /zap/wrk/testreport.html

          
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: "zapmainsciam"
          path: "${{ github.workspace }}/ops_utils/zap/*"  

