name: Baseline.yml

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  security-events: write
  issues: write

jobs:
  zap_scan_scientificamerican:
    name: Run ZAP Baseline Scan for scientificamerican.com
    runs-on: ubuntu-latest
    # runs-on: [sciam, self-hosted, linux]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug Paths
        run: |
          pwd
          ls -lah
          ls -lah $GITHUB_WORKSPACE

      - name: Ensure beta directory exists
        run: mkdir -p $GITHUB_WORKSPACE/beta


      - name: Check if beta directory exists
        run: ls -lah $GITHUB_WORKSPACE/beta

      - name: Run ZAP Scan
        run: |
          docker run -v $GITHUB_WORKSPACE/beta:/zap/wrk/beta:rw \
          -t ghcr.io/zaproxy/zaproxy:stable \
          zap-baseline.py -t https://www.scientificamerican.com -g /zap/wrk/beta/baseline.conf -r /zap/wrk/testreport.html



      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: "zapsciam"
          path: "${{ github.workspace }}/ops_utils/zap/*" 


  zap_scan_main_scientificamerican:
    name: Run ZAP Baseline Scan for main.scientificamerican.com
    runs-on: ubuntu-latest
    # runs-on: [sciam, self-hosted, linux]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug Paths
        run: |
          pwd
          ls -lah
          ls -lah $GITHUB_WORKSPACE

      - name: Ensure beta directory exists
        run: mkdir -p $GITHUB_WORKSPACE/beta


      - name: Check if beta directory exists
        run: ls -lah $GITHUB_WORKSPACE/beta

      - name: Run ZAP Scan
        run: |
          docker run -v $GITHUB_WORKSPACE/beta:/zap/wrk/beta:rw \
          -t ghcr.io/zaproxy/zaproxy:stable \
          zap-baseline.py -t https://www.scientificamerican.com -g /zap/wrk/beta/baseline.conf -r /zap/wrk/testreport.html

          
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: "zapmainsciam"
          path: "${{ github.workspace }}/ops_utils/zap/*"  

