name: Run ZAProxy Baseline Scans

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  security-events: write
  issues: write

jobs:
  zap_scan_scientificamerican:
    name: Run ZAP Baseline Scan for scientificamerican.com
    runs-on: ubuntu-latest
    # runs-on: [sciam, self-hosted, linux]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure baseline_rules.tsv exists
        run: |
          mkdir -p ops_utils/zap

          if [ ! -f ops_utils/zap/baseline_rules.tsv ]; then
            echo "WARN-NEW: Content Security Policy (CSP) Header Not Set 10038	IGNORE" > ops_utils/zap/baseline_rules.tsv
            echo "Created a default baseline_rules.tsv file."
          else
            echo "baseline_rules.tsv already exists. Skipping creation. "
          fi

      - name: Run ZAP Baseline Scan
        id: zap_scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: "https://www.scientificamerican.com/"
          fail_action: false
          rules_file_name: "ops_utils/zap/baseline_rules.tsv"
          docker_name: "ghcr.io/zaproxy/zaproxy:stable"
          issue_title: "ZAP Scan Baseline Report - scientificamerican.com"
          allow_issue_writing: true
          artifact_name: "zap_scan_scientificamerican.com"

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap_scan_scientificamerican
          path: zap_scan/*

  zap_scan_main_scientificamerican:
    name: Run ZAP Baseline Scan for main.scientificamerican.com
    runs-on: ubuntu-latest
    # runs-on: [sciam, self-hosted, linux]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure baseline_rules.tsv exists
        run: |
          mkdir -p ops_utils/zap

          if [ ! -f ops_utils/zap/baseline_rules.tsv ]; then
            echo "WARN-NEW: Content Security Policy (CSP) Header Not Set 10038	IGNORE" > ops_utils/zap/baseline_rules.tsv
            echo "Created a default rules.tsv file."
          else
            echo "baseline_rules.tsv already exists. Skipping creation. "
          fi

      - name: Run ZAP Baseline Scan
        id: zap_scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: " https://main-www.scientificamerican.com"
          fail_action: false
          rules_file_name: "ops_utils/zap/baseline_rules.tsv"
          docker_name: "ghcr.io/zaproxy/zaproxy:stable"
          issue_title: "ZAP Scan Baseline Report - main_scientificamerican.com"
          allow_issue_writing: true
          artifact_name: "zap_scan_main-www.scientificamerican.com"

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap_scan_main.scientificamerican
  #         path: zap_scan/*

