name: Monthly ZAP Baseline Scan

on:
  schedule:
    - cron: "0 0 1 * *"  # Runs at midnight UTC on the 1st of every month
  workflow_dispatch:

jobs:
  zap_scan:
    name: Run ZAP Baseline Scan
    runs-on: ubuntu-latest # Change if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure .zap/rules.tsv exists
        run: |
          if [ ! -f .zap/rules.tsv ]; then
            echo "rules.tsv file is missing! Exiting..."
            exit 1
          fi

      - name: Run ZAP Baseline Scan
        id: zap_scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: "https://hisyed.live"
          fail_action: false
          rules_file_name: ".zap/rules.tsv"
          docker_name: "ghcr.io/zaproxy/zaproxy:stable"
          issue_title: "ZAP Scan Baseline Report"
          allow_issue_writing: true
          artifact_name: "zap_scan"

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report_html.html

      - name: Notify Slack
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_SAWEBTEAM }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "⚡ *ZAP Baseline Scan Completed* ⚡\n\n*Target:* https://hisyed.live\n\n*Warnings Found:* 11\n\n*Full Report:* (See GitHub Artifacts)",
              "icon_emoji": ":zap:"
            }
