name: Monthly ZAP Baseline Scan

on:
  schedule:
    - cron: "0 0 1 * *"  # Runs at midnight UTC on the 1st of every month
  workflow_dispatch:

jobs:
  zap_scan:
    name: Run ZAP Baseline Scan
    runs-on: ubuntu-latest  # Change this if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ZAP Baseline Scan
        id: zap_scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: "https://hisyed.live"
          fail_action: false  # Prevents job failure due to warnings
          # cmd_options: "-config scanner.reportOnly=true"  # Alternative to `.zap/rules.tsv`
          docker_name: ghcr.io/zaproxy/zaproxy:stable
          artifact_name: zap_scan
          allow_issue_writing: false  # Prevents creating GitHub issues automatically
          format: json

      - name: Process ZAP JSON Report (Remove High-Risk Alerts)
        run: jq '.site[].alerts | map(select(.riskcode | contains("3") | not))' report_json.json > filtered_report.json

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report_html.html

      - name: Notify Slack
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_SAWEBTEAM }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "⚡ *ZAP Baseline Scan Completed* ⚡\n\n*Target:* https://hisyed.live\n\n*Summary:* ```${{ steps.zap_scan.outputs.summary }}```",
              "icon_emoji": ":zap:"
      
